org: serverlesscloud
app: multi-cloud-benchmark
service: gcp-nodejs8

provider:
  name: google
  stage: dev
  memorySize: 1024
  runtime: nodejs8
  region: us-east4
  project: serverless-cloud-benchmarks
  credentials: ~/.gcloud/serverless-cloud-benchmarks.json

plugins:
  - serverless-google-cloudfunctions

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**

functions:
  gcp-nodejs8-hello:
    handler: hello
    events:
      - http: gcp-nodejs8/hello
