org: serverlesscloud
app: multi-cloud-benchmark
service: gcp-go111

provider:
  name: google
  memorySize: 1024
  runtime: go111
  region: us-east4
  project: serverless-cloud-benchmark
  credentials: ~/.gcloud/benchmark.json # path must be absolute

plugins:
  - serverless-google-cloudfunctions

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**

functions:
  gcp-go111-hello:
    handler: hello
    events:
      - http: /hello