org: serverlesscloud
app: multi-cloud-benchmark
service: gcp-python37

provider:
  name: google
  memorySize: 1024
  runtime: python37
  region: us-east4
  project: serverless-cloud-benchmarks
  credentials: ~/.gcloud/serverless-cloud-benchmarks.json # path must be absolute

plugins:
  - serverless-google-cloudfunctions

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**

functions:
  gcp-python37-hello:
    handler: hello
    events:
      - http: gcp-python37/hello
