org: serverlesscloud
app: multi-cloud-benchmark
service: aws-python2-7

provider:
  name: aws
  runtime: python2.7

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get
