org: serverlesscloud
app: multi-cloud-benchmark
service: aws-python3-6

provider:
  name: aws
  runtime: python3.6

functions:
  hello:
    handler: handler.hello

    events:
      - http:
          path: /
          method: get
